# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHAdz3khx5IlKC-eSOA_hFTlBvHhB-vA
"""

!pip install streamlit

!pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# import numpy as np
# from PIL import Image
# from lang_sam import LangSAM
# from diffusers import StableDiffusionInpaintPipeline
# 
# # --- EXACT LOGIC START ---
# @st.cache_resource
# def load_models():
#     sam_model = LangSAM()
#     pipe = StableDiffusionInpaintPipeline.from_pretrained(
#         "runwayml/stable-diffusion-inpainting",
#         torch_dtype=torch.float16,
#         revision="fp16"
#     ).to("cuda")
#     return sam_model, pipe
# 
# # UI Setup
# st.title("T4 GPU Inpainter")
# uploaded_file = st.file_uploader("Image", type=["jpg", "png", "jpeg"])
# src_text = st.text_input("Object", "sunglasses")
# tgt_text = st.text_input("Replace with", "goggles")
# 
# if uploaded_file:
#     img = Image.open(uploaded_file).convert("RGB")
#     st.image(img, width=300)
# 
#     if st.button("Run Logic"):
#         sam, pipe = load_models()
# 
#         # EXACT NOTEBOOK LOGIC
#         masks, boxes, phrases, logits = sam.predict(img, src_text)
# 
#         if len(masks) > 0:
#             mask_np = masks[0].cpu().numpy()
#             mask_pil = Image.fromarray((mask_np * 255).astype(np.uint8))
# 
#             # Using exact notebook resizing and calling convention
#             result = pipe(
#                 prompt=tgt_text,
#                 image=img.resize((512, 512)),
#                 mask_image=mask_pil.resize((512, 512))
#             ).images[0]
# 
#             st.image(result.resize(img.size), caption="Output")
# # --- EXACT LOGIC END ---

from google.colab.output import eval_js

# Get your proxy URL
print("Click here to open the app:")
print(eval_js("google.colab.kernel.proxyPort(8501)"))

# Run without forcing offline mode so it can resolve the "snapshot" error
!streamlit run app.py --server.port 8501 --server.headless True --server.enableCORS False --server.enableXsrfProtection False

